- name: Install dependencies
  apt:
    pkg:
      name:
      - git


- name: Add user to group 'cldinf'
  user:
    name: cldinf
    comment: "Service User for Kanban Application"
    append: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

